spring:
  application:
    name: PagFut

  datasource:
    url: jdbc:h2:mem:pagfut
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

mercadopago:
  access:
    token:
